import = [
  "~/.config/alacritty/themes/gruvbox-dark-hard.toml"
]

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1"

[shell]
program = "/bin/zsh"


[window]
option_as_alt = "Both"
opacity = 0.95
decorations = "none"

[font]
size = 10.5

  [font.normal]
  # family = "FiraCode Nerd Font"
  family = "JetBrainsMono Nerd Font"
  # style = "Medium"
