import = [
  "~/.config/alacritty/themes/gruvbox-dark-hard.toml"
]

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1"

[shell]
program = "/bin/zsh"


[window]
opacity = 0.85
option_as_alt = "Both"
decorations = "none"

[font]
size = 12.0

  [font.normal]
  family = "FiraCode Nerd Font Mono"
  style = "Retina"
