[general]
import = [
  "~/.config/alacritty/themes/gruber-darker.toml"
]

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[terminal]
  [terminal.shell]
  program = "/bin/zsh"


[window]
option_as_alt = "OnlyLeft"
opacity = 0.95
# decorations = "none" # uncomment to the close, minimize and maximize bar

[font]
size = 11.5

  [font.normal]
  family = "JetBrainsMono Nerd Font"
