#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. "$SCRIPT_DIR/utils.sh"

help(){
  printf "Usage: bob (command)\n"
  printf "\nCommands:\n"
  printf "\tinstall\n\t\t Install specified package.\n\n"
  printf "\tbuild\n\t\t Alias for install. Because bob the builder.\n\n"
  printf "\tuninstall\n\t\t Uninstall specified package.\n\n"
  printf "\tremove\n\t\t Alias for uninstall.\n\n"
}

build_all(){
  if ask "Are you sure you want to build all?"; then
    "${SCRIPT_DIR}/alacritty.sh" build
    "${SCRIPT_DIR}/fonts.sh" build
    "${SCRIPT_DIR}/regolith.sh" build
    "${SCRIPT_DIR}/i3.sh" build
  else
    printf "Not building all\n"
  fi
}

cmd=""
case $1 in
  "thebuilder")
    printf "Bob the builder, can we build it?\n"
    build_all
    printf "Bob the builder, yes we can!\n"
    exit 0
    ;;
  "build"|"install")
    cmd="install"
    ;;
  "remove"|"uninstall")
    cmd="uninstall"
    ;;
  "help"|"--help"|"-h")
    help
    exit 0
    ;;
  "")
    echo "Bob needs a command, try bob --help"
    exit 1
    ;;
  *)
    printf "Unknown command: %s\n" "$1"
    help
    exit 1
    ;;
esac

arg=$2
case $arg in
  "alacritty"|"fonts"|"regolith"|"i3")
    if ask "Are you sure you want to $cmd $arg?"; then
      "${SCRIPT_DIR}/${arg}.sh" "$cmd"
    else
      printf "Not %sing %s\n" "$cmd" "$arg"
    fi
    exit 0
    ;;
  "pkgs"|"gopkgs")
    if [[ $cmd = "uninstall" ]]; then
      printf "Bob can't uninstall these packages for you\n"
      exit 1
    fi
    ;;
  "")
    printf "Bob needs a package to %s\n" "$cmd"
    exit 1
    ;;
  *)
    printf "Unknown package: %s\n" "$2"
    exit 1
    ;;
esac

if [[ $cmd = "install" ]]; then
case $2 in
  "gopkgs")
    if ask "Are you sure you want to go packages?"; then
      install_go_pkgs
    else
      printf "Not installing go packages\n"
    fi
    ;;
  *)
    printf "Unknown package: %s\n" "$2"
    exit 1
    ;;
esac
fi
