[tools]
bat = "latest"
bat-extras = "latest"
btop = { version = "latest", os = ["linux"] }
deno = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
node = "24"
"npm:bash-language-server" = "latest"
"npm:oxlint-tsgolint" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
opencode = "latest"
oxfmt = "latest"
oxlint = "latest"
pnpm = "latest"
prettier = "latest"
ripgrep = "latest"
ruff = "latest"
rust = { version = "latest", components = "rust-analyzer" }
stylua = "latest"
tmux = "latest"
tree-sitter = "latest"
ty = "latest"
usage = "latest"
uv = "latest"
zoxide = "latest"
lua-language-server = "latest"
