gui:
  theme:
    activeBorderColor:
      - '#00ff00'
    inactiveBorderColor:
      - '#2d5a27'
    optionsTextColor:
      - '#CC8C3C'
    selectedLineBgColor:
      - '#644319'
    cherryPickedCommitBgColor:
      - '#458588'
git:
  overrideGpg: true
os:
  editPreset: nvim
notARepository: 'quit'
