#zmodload zsh/zprof
_not_inside_tmux() { [[ -z "$TMUX" ]] }

ensure_tmux_is_running() {
  if _not_inside_tmux; then
    sh ~/.config/tmux/tat.sh
  fi
}
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
ensure_tmux_is_running

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
source ~/powerlevel10k/powerlevel10k.zsh-theme
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=2048
SAVEHIST=2048
setopt autocd
bindkey -e # Use emacs keybindings even if our EDITOR is set to vi

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '~/.zshrc'
fpath+=~/.zfunc
fpath+=~/.zsh/zsh-completions/src
# Use modern completion system
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
autoload -Uz compinit
compinit -D
# End of lines added by compinstall

# Ctrl-e open cli in nvim
export EDITOR='nvim'
autoload edit-command-line
zle -N edit-command-line
bindkey "^E" edit-command-line

setopt histignorealldups sharehistory
alias top=htop 
alias vim=nvim 
alias lg=lazygit
export FZF_DEFAULT_OPTS='--preview "bat --color=always --style=numbers --line-range=:500 {}"'

eval "$(fnm env --use-on-cd)"
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh


eval "$(batpipe)"
#zprof
